version: 0.2
phases:
  pre_build:
    commands:
      - make roles
  build:
    commands:
      - make generate/build /codebuild
      - make generate/sandbox /codebuild
      - make generate/staging /codebuild
      - make generate/users /codebuild
artifacts:
  files:
    - build/*
