# Assume Role
- name: Assume Role
  hosts: "{{ env }}"
  gather_facts: no
  roles:
    - aws-sts

# Deploy CloudFormation Stack
- name: Stack Deployment
  hosts: "{{ env }}"
  gather_facts: no
  environment: "{{ Sts.Credentials }}"
  roles:
    - aws-cloudformation